# Generated by Django 5.0.1 on 2024-01-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(upload_to='administrator/file_uploads/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.product')),
            ],
        ),
    ]
