# Generated by Django 5.0.1 on 2024-01-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_faq'),
        ('authentication', '0004_remove_consumer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='reply',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reply', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.consumer')),
            ],
        ),
    ]
