# Generated by Django 5.0.1 on 2024-01-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
                ('paid_amount', models.FloatField()),
                ('order_placed', models.DateTimeField()),
                ('delivery_address', models.TextField()),
            ],
        ),
    ]
