# Generated by Django 5.0.1 on 2024-01-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_order_user_alter_photo_product'),
        ('authentication', '0006_alter_consumer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='authentication.consumer'),
        ),
    ]
