# Generated by Django 5.0.1 on 2024-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_order_quantity_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
