# Generated by Django 5.0.1 on 2024-01-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
