# Generated by Django 5.0.1 on 2024-01-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_alter_order_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
