# Generated by Django 5.0.1 on 2024-01-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_category_consumer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
