# Generated by Django 5.0.1 on 2024-01-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='address',
        ),
    ]
