# Generated by Django 5.0.1 on 2024-01-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_consumer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phone_no',
            field=models.CharField(help_text='Enter phone number', max_length=15),
        ),
    ]
